// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luspkshuwhnsltnhrskg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1c3Brc2h1d2huc2x0bmhyc2tnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzA5MDEsImV4cCI6MjA2OTU0NjkwMX0.DJESPVTUoSYXCQ4Azdr3cpmYAYyE-gFMkeLsrbr7Kmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});